### ISSUE TITLE
Provider keeps crashing

### ISSUE THREAD

**Issue by xenalite** [imperva/terraform-provider-incapsula#32]
I applied a Terraform configuration successfully with a site, data center, servers and some rules.
I am re-executing `terraform plan` after applying a previous plan. I am expecting a "no-changes" message. Instead, Terraform crashes - please see the attached `crash.log` file.

[crash.log](https://github.com/imperva/terraform-provider-incapsula/files/4306992/crash.log)

I observed this behaviour as well while experimenting with local state file:
- When I take out all resources from the state file and re-run plan, it doesn't crash.
- I tried to narrow down which resources in the state start crashing.
- I can add back in all resources except for `incapsula_data_center_server` type without crashing.
- As soon as I add `incapsula_data_center_server` resources back to state file, the plan command crashes.

Example of `incapsula_data_center_server` resource in state file:
```
{
      "module": "module.www_my_domain_redacted_data_center_production",
      "mode": "managed",
      "type": "incapsula_data_center_server",
      "name": "reverse_proxy_production_02",
      "provider": "provider.incapsula",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "dc_id": "2116581",
            "id": "3949106",
            "is_enabled": "true",
            "is_standby": "false",
            "server_address": "<public_ip_redacted>",
            "site_id": "95769653"
          },
          "private": "<private>",
          "dependencies": [
            "incapsula_site.www_my_domain_redacted",
            "module.www_my_domain_redacted_data_center_production.incapsula_data_center.reverse_proxy_production"
          ]
        }
      ]
    }
```

Command used:
```
terraform plan -out tfplan -var-file="local.tfvars"
```

Provider used:
```
provider "incapsula" {
  version = "=2.1.0"
  api_id = var.incapsula_api_id
  api_key = var.incapsula_api_key
}
```

Terraform version:
```
Terraform v0.12.20
+ provider.incapsula v2.1.0
```

**Comment by xenalite** [comment]
I was looking at one of the error messages:
```
2020-03-09T13:52:17.251Z [DEBUG] plugin.terraform-provider-incapsula_v2.1.0_x4.exe: panic: interface conversion: interface {} is string, not int
2020-03-09T13:52:17.251Z [DEBUG] plugin.terraform-provider-incapsula_v2.1.0_x4.exe: 
2020-03-09T13:52:17.251Z [DEBUG] plugin.terraform-provider-incapsula_v2.1.0_x4.exe: goroutine 475 [running]:
2020-03-09T13:52:17.251Z [DEBUG] plugin.terraform-provider-incapsula_v2.1.0_x4.exe: github.com/terraform-providers/terraform-provider-incapsula/incapsula.resourceDataCenterServerRead(0xc0002df180, 0x10246a0, 0xc000441c50, 0xc0002df180, 0x0)
2020-03-09T13:52:17.251Z [DEBUG] plugin.terraform-provider-incapsula_v2.1.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-incapsula/incapsula/resource_data_center_server.go:141 +0xa1d
2020-03-09T13:52:17.251Z [DEBUG] plugin.terraform-provider-incapsula_v2.1.0_x4.exe: github.com/terraform-providers/terraform-provider-incapsula/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000176c00, 0xc000620b40, 0x10246a0, 0xc000441c50, 0xc0006346f8, 0x0, 0x0)
2020-03-09T13:52:17.251Z [DEBUG] plugin.terraform-provider-incapsula_v2.1.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-incapsula/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:455 +0x120
2020-03-09T13:52:17.251Z [DEBUG] plugin.terraform-provider-incapsula_v2.1.0_x4.exe: github.com/terraform-providers/terraform-provider-incapsula/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00012e4d8, 0x129a260, 0xc00053f530, 0xc000620a50, 0xc00012e4d8, 0xc00053f530, 0xc00025dbd0)
2020-03-09T13:52:17.251Z [DEBUG] plugin.terraform-provider-incapsula_v2.1.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-incapsula/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:525 +0x3de
2020-03-09T13:52:17.251Z [DEBUG] plugin.terraform-provider-incapsula_v2.1.0_x4.exe: github.com/terraform-providers/terraform-provider-incapsula/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x1008b40, 0xc00012e4d8, 0x129a260, 0xc00053f530, 0xc00011c780, 0x0, 0x129a260, 0xc00053f530, 0xc000258320, 0x91)
2020-03-09T13:52:17.251Z [DEBUG] plugin.terraform-provider-incapsula_v2.1.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-incapsula/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3153 +0x245
2020-03-09T13:52:17.251Z [DEBUG] plugin.terraform-provider-incapsula_v2.1.0_x4.exe: github.com/terraform-providers/terraform-provider-incapsula/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003a8160, 0x12a5620, 0xc000059b00, 0xc000520f00, 0xc000128de0, 0x1b53170, 0x0, 0x0, 0x0)
2020-03-09T13:52:17.251Z [DEBUG] plugin.terraform-provider-incapsula_v2.1.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-incapsula/vendor/google.golang.org/grpc/server.go:995 +0x46d
2020-03-09T13:52:17.251Z [DEBUG] plugin.terraform-provider-incapsula_v2.1.0_x4.exe: github.com/terraform-providers/terraform-provider-incapsula/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0003a8160, 0x12a5620, 0xc000059b00, 0xc000520f00, 0x0)
2020-03-09T13:52:17.251Z [DEBUG] plugin.terraform-provider-incapsula_v2.1.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-incapsula/vendor/google.golang.org/grpc/server.go:1275 +0xdad
2020-03-09T13:52:17.251Z [DEBUG] plugin.terraform-provider-incapsula_v2.1.0_x4.exe: github.com/terraform-providers/terraform-provider-incapsula/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00002a2a0, 0xc0003a8160, 0x12a5620, 0xc000059b00, 0xc000520f00)
2020-03-09T13:52:17.251Z [DEBUG] plugin.terraform-provider-incapsula_v2.1.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-incapsula/vendor/google.golang.org/grpc/server.go:710 +0xa6
2020-03-09T13:52:17.251Z [DEBUG] plugin.terraform-provider-incapsula_v2.1.0_x4.exe: created by github.com/terraform-providers/terraform-provider-incapsula/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2020-03-09T13:52:17.251Z [DEBUG] plugin.terraform-provider-incapsula_v2.1.0_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-incapsula/vendor/google.golang.org/grpc/server.go:708 +0xa8
```
I thought there may be something wrong with types, so tried to trace down the issue with my limited Go knowledge.

I found the issue in this file: `incapsula/resource_data_center_server.go` line 141.
```
log.Printf("[INFO] Incapsula Data Center Server ID %s for Site ID %d has already been deleted: %s\n", d.Id(), d.Get("site_id").(int), err)
```
Site ID is cast to int. I changed the code to not do the cast, recompiled provider and re-ran the plan. The provider succeeded with new code. I think it makes sense considering line 114 in the same file does not do cast to int on the same value:
```
log.Printf("[INFO] Incapsula Site ID %s has already been deleted: %s\n", d.Get("site_id"), err)
```

By the way, I have deleted many data centers and their servers over the course of this testing, so this may explain as to how I got into this condition in the first place.
