### ISSUE TITLE
Import of incapsula_policy_asset_association causes plugin crash

### ISSUE THREAD

**Issue by Sudneo** [imperva/terraform-provider-incapsula#93]
## Description

Using a configuration such as:

```
resource "incapsula_site" "my_site_com" {
    domain = "my.site.com"
}

resource "incapsula_policy" "site_com_policy" {
    name = "Policy"
    enabled = "true"
    policy_type = "WHITELIST"
    description = "Whatever"
    policy_settings = jsonencode(
    [
	{
	    "settingsAction": "ALLOW",
	    "policySettingType": "IP",
	    "data": {
		"ips": [
		    "192.168.0.1",
		]
	    }
	},
    ]
    )
}

resource "incapsula_policy_asset_association" "site_com_policy_association" {
  policy_id  = incapsula_policy.site_com_policy.id
  asset_id   = incapsula_site.my_site_com.id 
  asset_type = "WEBSITE"
}
```
By running 

```
terraform import incapsula_policy_asset_association.site_com_policy_association $SITE_ID|$POLICY_ID
```

The plugin crashes.

## Error

The crash log is the following:

```
panic: runtime error: index out of range [1] with length 1

goroutine 83 [running]:
github.com/terraform-providers/terraform-provider-incapsula/incapsula.resourcePolicyAssetAssociationRead(0xc000603400, 0x10c3fe0, 0xc0001200d0, 0x1aed070, 0x1122658)
	github.com/terraform-providers/terraform-provider-incapsula/incapsula/resource_policy_asset_association.go:70 +0xaab
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0002a28c0, 0x13516c0, 0xc0007baf40, 0xc000603400, 0x10c3fe0, 0xc0001200d0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:335 +0x1e9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0002a28c0, 0x13516c0, 0xc0007baf40, 0xc0004af490, 0x10c3fe0, 0xc0001200d0, 0xc0008002d0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:624 +0x1c2
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0006ecb80, 0x13516c0, 0xc0007baf40, 0xc0007baf80, 0xc0007baf40, 0x1033140, 0x107e700)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:575 +0x42f
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc00048ddc0, 0x13516c0, 0xc0007baf40, 0xc000081da0, 0xc00048ddc0, 0xc00015c0f0, 0xc0005dcba0)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x101
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x107e700, 0xc00048ddc0, 0x1351780, 0xc00015c0f0, 0xc000081d40, 0x0, 0x1351780, 0xc00015c0f0, 0xc000139b80, 0x72)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000232a80, 0x135eae0, 0xc000783380, 0xc0002a4500, 0xc0001c8b10, 0x1ab1e70, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x50a
google.golang.org/grpc.(*Server).handleStream(0xc000232a80, 0x135eae0, 0xc000783380, 0xc0002a4500, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xcfd
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0001284e0, 0xc000232a80, 0x135eae0, 0xc000783380, 0xc0002a4500)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x204
```

It seems some trivial out-of-bound error, but I couldn't figure out a way around it.

**Comment by joeymoore** [comment]
@Sudneo 
The docs show that you need the asset type as well "WEBSITE".
$ terraform import incapsula_policy_asset_association.example-policy-asset-association policy_id/asset_id/asset_type
Also, are you using "|" or "/"?

**Comment by Sudneo** [comment]
@joeymoore Thanks for getting back to this, I actually understood the doc as a 'either', I didn't understand that you actually need to pass all the three different parameters. I will try with that, and edit the issue. 

Thank you

**Comment by Sudneo** [comment]
Thanks one more time @joeymoore , with all the parameters supplied indeed no error occurs.

In the hope of making at least partially up for the time wasted, would it be a good idea to modify the resourcePolicyAssettAssociationRead function such as (wording and naming is just for example purpose).

```
attributes := strings.Split(d.Id(), "/")
	if len(attributes) != 3 {
		log.Printf("[ERROR] Not enough arguments supplied to read Incapsula Policy Asset Associations")
		return fmt.Errorf("Not enough arguments")
	}

	policyID := attributes[0]
	assetID := attributes[1]
	assetType := attributes[2]
```

I believe that this way the panic should be avoided and maybe an error message can be passed to the user?
